#!/bin/bash

FILE=$1

function help {
    echo "usage: ${0} <month> <search>"
    exit 1 
}

if  [ -z $FILE ]; then
FILE=tmp
fi

gcc -Wall ${FILE}\.c -o $FILE

chmod +x ./$FILE

echo "$FILE has been compiled"